//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credits {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Credits.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to о Газета.Ru.
        /// </summary>
        public static string AboutCredits {
            get {
                return ResourceManager.GetString("AboutCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to о приложении.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Газета.Ru.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to статья.
        /// </summary>
        public static string ArticleAppBarText {
            get {
                return ResourceManager.GetString("ArticleAppBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to статьи.
        /// </summary>
        public static string ArticlesTitle {
            get {
                return ResourceManager.GetString("ArticlesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to автоопределение города.
        /// </summary>
        public static string AutoSelectCity {
            get {
                return ResourceManager.GetString("AutoSelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to автообновление.
        /// </summary>
        public static string Autoupdate {
            get {
                return ResourceManager.GetString("Autoupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для перехода по ссылке будет открыт браузер.
        /// </summary>
        public static string BrowserQuery {
            get {
                return ResourceManager.GetString("BrowserQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to автоочистка кэша.
        /// </summary>
        public static string CacheClear {
            get {
                return ResourceManager.GetString("CacheClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to время жизни кэша.
        /// </summary>
        public static string CacheLifetime {
            get {
                return ResourceManager.GetString("CacheLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сайт: .
        /// </summary>
        public static string Cite {
            get {
                return ResourceManager.GetString("Cite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to комментарии.
        /// </summary>
        public static string CommentsAppBarText {
            get {
                return ResourceManager.GetString("CommentsAppBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует подключение к интернету. Невозможно выполнить операцию.
        /// </summary>
        public static string ConnectionAbsence {
            get {
                return ResourceManager.GetString("ConnectionAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поключение к интернету потеряно.
        /// </summary>
        public static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to разработчик.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка статей.
        /// </summary>
        public static string DownloadArticles {
            get {
                return ResourceManager.GetString("DownloadArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to добавить.
        /// </summary>
        public static string FavoritesAddAppBarText {
            get {
                return ResourceManager.GetString("FavoritesAddAppBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удалить.
        /// </summary>
        public static string FavoritesDelAppBarText {
            get {
                return ResourceManager.GetString("FavoritesDelAppBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to избранное.
        /// </summary>
        public static string FavoritesTitle {
            get {
                return ResourceManager.GetString("FavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 дней.
        /// </summary>
        public static string FiveDays {
            get {
                return ResourceManager.GetString("FiveDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to уменьшить.
        /// </summary>
        public static string FontMinusAppBarText {
            get {
                return ResourceManager.GetString("FontMinusAppBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to увеличить.
        /// </summary>
        public static string FontPlusAppBarText {
            get {
                return ResourceManager.GetString("FontPlusAppBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to частота обновления.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} пунктов.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} пункт.
        /// </summary>
        public static string Items1_21 {
            get {
                return ResourceManager.GetString("Items1_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} пункта.
        /// </summary>
        public static string Items2_3_4 {
            get {
                return ResourceManager.GetString("Items2_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ограничение списков.
        /// </summary>
        public static string ListLimit {
            get {
                return ResourceManager.GetString("ListLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to каждую {0} минуту.
        /// </summary>
        public static string Minutes1_21 {
            get {
                return ResourceManager.GetString("Minutes1_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to каждые {0} минуты.
        /// </summary>
        public static string Minutes1_5_21_25 {
            get {
                return ResourceManager.GetString("Minutes1_5_21_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to каждые {0} минут.
        /// </summary>
        public static string Minutes4_21_24 {
            get {
                return ResourceManager.GetString("Minutes4_21_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to новости.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы еще ничего не добавили в избранное.
        /// </summary>
        public static string NothingAddedToFavorites {
            get {
                return ResourceManager.GetString("NothingAddedToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По запросу &quot;{0}&quot; в заметках ничего найдено не было.
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to для работы раздела необходимо.
        /// </summary>
        public static string OfflineLine1 {
            get {
                return ResourceManager.GetString("OfflineLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подключение к интернету.
        /// </summary>
        public static string OfflineLine2 {
            get {
                return ResourceManager.GetString("OfflineLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потеряно подключение к интернету. Работа приложения будет продолжена в автономном режиме.
        /// </summary>
        public static string OfflineStartupText {
            get {
                return ResourceManager.GetString("OfflineStartupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 день.
        /// </summary>
        public static string OneDay {
            get {
                return ResourceManager.GetString("OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 неделя.
        /// </summary>
        public static string OneWeek {
            get {
                return ResourceManager.GetString("OneWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to фото.
        /// </summary>
        public static string PhotosTitle {
            get {
                return ResourceManager.GetString("PhotosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to обновить.
        /// </summary>
        public static string RefreshAppBarText {
            get {
                return ResourceManager.GetString("RefreshAppBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удалить из избранного.
        /// </summary>
        public static string RemoveFromFavorites {
            get {
                return ResourceManager.GetString("RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сохранить.
        /// </summary>
        public static string SaveAppBarText {
            get {
                return ResourceManager.GetString("SaveAppBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to поиск.
        /// </summary>
        public static string SearchAppBarText {
            get {
                return ResourceManager.GetString("SearchAppBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to поиск.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отправить статью.
        /// </summary>
        public static string SendArticle {
            get {
                return ResourceManager.GetString("SendArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to настройки.
        /// </summary>
        public static string SettingsAppBarText {
            get {
                return ResourceManager.GetString("SettingsAppBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отправить.
        /// </summary>
        public static string ShareAppBarText {
            get {
                return ResourceManager.GetString("ShareAppBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string ShareDialogTitle {
            get {
                return ResourceManager.GetString("ShareDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 дня.
        /// </summary>
        public static string TwoDays {
            get {
                return ResourceManager.GetString("TwoDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to версия.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
